//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboMB12.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Dernier_Fichier_csv {
            get {
                return ((string)(this["Dernier_Fichier_csv"]));
            }
            set {
                this["Dernier_Fichier_csv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Dernier_Fichier_Modele {
            get {
                return ((string)(this["Dernier_Fichier_Modele"]));
            }
            set {
                this["Dernier_Fichier_Modele"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATTESTATION 2018")]
        public string Titre_PDF {
            get {
                return ((string)(this["Titre_PDF"]));
            }
            set {
                this["Titre_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Nous soussignés, la Société BM12 Informatique, certifions que,
                                        
                                        
                     {RAISON_SOCIALE}
                     {ADRESSE_LIGNE1}
                     
                     {CP} {VILLE}
                                     
                                         
 a suivi une formation aux logiciels Informatiques de {HEURE} heures, durant l'année,
 dispensée par Brigitte MAYANOBE, formatrice au sein de notre établissement.
 Enregistré sous le numéro 73 12 00583 12
 En foi de quoi, nous lui délivrons cette attestation pour lui servir et faire valoir ce que de droit.
                                         
                                                                            
                                         
                                      Les Vernhes, le 24/01/2018
                                                                          
                                     
                                      Gérante BM12
                                      Brigitte Mayanobe

")]
        public string Corps_PDF {
            get {
                return ((string)(this["Corps_PDF"]));
            }
            set {
                this["Corps_PDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Abonnement BM12")]
        public string Sujet_Mail {
            get {
                return ((string)(this["Sujet_Mail"]));
            }
            set {
                this["Sujet_Mail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bonjour\r\n\r\n\r\nVeuilez trouver ci-joint votre attestation de formation.\r\n\r\n\r\nCordia" +
            "lement,\r\nBrigitte Mayanobe")]
        public string Corps_Mail {
            get {
                return ((string)(this["Corps_Mail"]));
            }
            set {
                this["Corps_Mail"] = value;
            }
        }
    }
}
