//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboMB12.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Dernier_Fichier_csv {
            get {
                return ((string)(this["Dernier_Fichier_csv"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Dernier_Fichier_Modele {
            get {
                return ((string)(this["Dernier_Fichier_Modele"]));
            }
            set {
                this["Dernier_Fichier_Modele"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATTESTATION FORMATION 2024")]
        public string Titre_PDF {
            get {
                return ((string)(this["Titre_PDF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attestation de formation BM12 2024")]
        public string Sujet_Mail {
            get {
                return ((string)(this["Sujet_Mail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"            Nous soussignés, la Société BM12 Informatique, certifions que,

					{CIVILITE} {INTERLOCUTEUR}
					
     a suivi une formation aux logiciels Informatiques de {HEURE} heures, durant l'année 2024,
					dispensée par Brigitte MAYANOBE, formatrice au sein de notre établissement.

					Enregistré sous le numéro 73 12 00583 12.

					En foi de quoi, nous lui délivrons cette attestation pour lui servir et faire valoir ce que         de droit.

					Les Vernhes, le 27/01/2025

					                                          Gérante BM12
					                                          Brigitte Mayanobe
				")]
        public string Corps_PDF {
            get {
                return ((string)(this["Corps_PDF"]));
            }
        }
    }
}
